apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: engine-ingress
  namespace: insurance
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - engine.showcase.service-b.org
      secretName: engine-tls
  rules:
    - host: engine.showcase.service-b.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: engine
                port:
                  number: 7001
